export enum AttrType {
  String,
  Bool
}

const NodeAttributes = {
  abbr: { name: "abbr", type: AttrType.String },
  accept: { name: "accept", type: AttrType.String },
  "accept-charset": { name: "accept-charset", type: AttrType.String },
  accesskey: { name: "accesskey", type: AttrType.String },
  async: { name: "async", type: AttrType.Bool },
  action: { name: "action", type: AttrType.String },
  align: { name: "align", type: AttrType.String },
  allow: { name: "allow", type: AttrType.String },
  allowfullscreen: { name: "allowfullscreen", type: AttrType.String },
  alt: { name: "alt", type: AttrType.String },
  as: { name: "as", type: AttrType.String },
  attributionsrc: { name: "attributionsrc", type: AttrType.String },
  autocapitalize: { name: "autocapitalize", type: AttrType.String },
  autocomplete: { name: "autocomplete", type: AttrType.String },
  autofocus: { name: "autofocus", type: AttrType.Bool },
  autoplay: { name: "autoplay", type: AttrType.Bool },
  blocking: { name: "blocking", type: AttrType.String },
  capture: { name: "capture", type: AttrType.String },
  checked: { name: "checked", type: AttrType.Bool },
  cite: { name: "cite", type: AttrType.String },
  class: { name: "class", type: AttrType.String },
  cols: { name: "cols", type: AttrType.String },
  colspan: { name: "colspan", type: AttrType.String },
  content: { name: "content", type: AttrType.String },
  contenteditable: { name: "contenteditable", type: AttrType.String },
  controls: { name: "controls", type: AttrType.Bool },
  coords: { name: "coords", type: AttrType.String },
  crossorigin: { name: "crossorigin", type: AttrType.String },
  data: { name: "data", type: AttrType.String },
  datetime: { name: "datetime", type: AttrType.String },
  default: { name: "default", type: AttrType.String },
  defer: { name: "defer", type: AttrType.Bool },
  dir: { name: "dir", type: AttrType.String },
  dirname: { name: "dirname", type: AttrType.String },
  disabled: { name: "disabled", type: AttrType.Bool },
  encoding: { name: "encoding", type: AttrType.String },
  enctype: { name: "enctype", type: AttrType.String },
  enterkeyhint: { name: "enterkeyhint", type: AttrType.String },
  fetchpriority: { name: "fetchpriority", type: AttrType.String },
  for: { name: "for", type: AttrType.String },
  formaction: { name: "formaction", type: AttrType.String },
  formmethod: { name: "formmethod", type: AttrType.String },
  formnovalidate: { name: "formnovalidate", type: AttrType.String },
  formtarget: { name: "formtarget", type: AttrType.String },
  hash: { name: "hash", type: AttrType.String },
  headers: { name: "headers", type: AttrType.String },
  height: { name: "height", type: AttrType.String },
  hidden: { name: "hidden", type: AttrType.String },
  high: { name: "high", type: AttrType.String },
  hostname: { name: "hostname", type: AttrType.String },
  href: { name: "href", type: AttrType.String },
  hreflang: { name: "hreflang", type: AttrType.String },
  "http-equiv": { name: "http-equiv", type: AttrType.String },
  id: { name: "id", type: AttrType.String },
  indeterminate: { name: "indeterminate", type: AttrType.Bool },
  inert: { name: "inert", type: AttrType.Bool },
  inputmode: { name: "inputmode", type: AttrType.String },
  integrity: { name: "integrity", type: AttrType.String },
  ismap: { name: "ismap", type: AttrType.Bool },
  kind: { name: "kind", type: AttrType.String },
  label: { name: "label", type: AttrType.String },
  lang: { name: "lang", type: AttrType.String },
  length: { name: "length", type: AttrType.String },
  list: { name: "list", type: AttrType.String },
  loop: { name: "loop", type: AttrType.Bool },
  low: { name: "low", type: AttrType.String },
  max: { name: "max", type: AttrType.String },
  maxlength: { name: "maxlength", type: AttrType.String },
  media: { name: "media", type: AttrType.String },
  method: { name: "method", type: AttrType.String },
  min: { name: "min", type: AttrType.String },
  minlength: { name: "minlength", type: AttrType.String },
  multiple: { name: "multiple", type: AttrType.Bool },
  muted: { name: "muted", type: AttrType.Bool },
  name: { name: "name", type: AttrType.String },
  nomodule: { name: "nomodule", type: AttrType.String },
  nonce: { name: "nonce", type: AttrType.String },
  novalidate: { name: "novalidate", type: AttrType.Bool },
  open: { name: "open", type: AttrType.Bool },
  optimum: { name: "optimum", type: AttrType.String },
  pathname: { name: "pathname", type: AttrType.String },
  pattern: { name: "pattern", type: AttrType.String },
  password: { name: "password", type: AttrType.String },
  placeholder: { name: "placeholder", type: AttrType.String },
  popover: { name: "popover", type: AttrType.String },
  popovertarget: { name: "popovertarget", type: AttrType.String },
  popovertargetaction: { name: "popovertargetaction", type: AttrType.String },
  poster: { name: "poster", type: AttrType.String },
  preload: { name: "preload", type: AttrType.String },
  readonly: { name: "readonly", type: AttrType.Bool },
  referrerpolicy: { name: "referrerpolicy", type: AttrType.String },
  rel: { name: "rel", type: AttrType.String },
  required: { name: "required", type: AttrType.Bool },
  reversed: { name: "reversed", type: AttrType.Bool },
  role: { name: "role", type: AttrType.String },
  rows: { name: "rows", type: AttrType.String },
  rowspan: { name: "rowspan", type: AttrType.String },
  sandbox: { name: "sandbox", type: AttrType.String },
  scope: { name: "scope", type: AttrType.String },
  selected: { name: "selected", type: AttrType.Bool },
  shape: { name: "shape", type: AttrType.String },
  size: { name: "size", type: AttrType.String },
  sizes: { name: "sizes", type: AttrType.String },
  slot: { name: "slot", type: AttrType.String },
  span: { name: "span", type: AttrType.String },
  spellcheck: { name: "spellcheck", type: AttrType.String },
  src: { name: "src", type: AttrType.String },
  srclang: { name: "srclang", type: AttrType.String },
  srcset: { name: "srcset", type: AttrType.String },
  start: { name: "start", type: AttrType.String },
  step: { name: "step", type: AttrType.String },
  tabindex: { name: "tabindex", type: AttrType.String },
  target: { name: "target", type: AttrType.String },
  title: { name: "title", type: AttrType.String },
  translate: { name: "translate", type: AttrType.Bool },
  type: { name: "type", type: AttrType.String },
  usemap: { name: "usemap", type: AttrType.String },
  value: { name: "value", type: AttrType.String },
  width: { name: "width", type: AttrType.String },
  wrap: { name: "wrap", type: AttrType.String }
} as const;

export interface NodeAttribute {
  name: string;
  type: AttrType;
}

export default NodeAttributes;